create table if not exists public.ramp_operations (
    id bigint generated by default as identity primary key,
    operation_date date not null,
    ramp_id text,
    shift text,
    vehicles_count integer default 0,
    containers_count integer default 0,
    created_at timestamptz default now()
);

comment on table public.ramp_operations is 'Daily ramp statistics including vehicles processed per shift.';
comment on column public.ramp_operations.operation_date is 'Calendar date for the operation';
comment on column public.ramp_operations.vehicles_count is 'Number of vehicles processed in the record';
comment on column public.ramp_operations.containers_count is 'Number of containers processed in the record';

grant select, insert, update, delete on table public.ramp_operations to service_role;

